### PR TITLE
7zip 21.07

### LINKED ISSUE #156: Please update branch 7zip_21.02
Please update branch 7zip_21.02 as 7-Zip 21.03 beta is out https://sourceforge.net/p/sevenzip/discussion/45797/thread/9f5b067368/

### PR DESCRIPTION
**Pull request by cielavenir**
closes #156

what I did was basically overwriting 21.07 onto 6c6ed1eba9ff0c0ded9323600f1f3c686d6b6692 and merged it to 7zip_21.02 HEAD.

However I have to say one thing: on c65ff523fbbba1b0fc5624b29d44a37db34cf8a5 you ran some code formatter on CPP/7zip/Archive/7z/7zHandler.cpp right? it broke almost everything and I had to check conflict carefully.
Next time please keep the changes very least including indentation.

also please name 672af56c463c2690b1f90fce3335800cc04abc39 "mirror" (or "7zip_mirror" or "upstream") on your repository for our ease afterwards.  

/cc @pashamcr @teoberi

### CODE REVIEW

**Comment by teoberi** [comment]
https://github.com/jinfeihan57/p7zip/issues/156#issuecomment-891433297
I don't know what will happen to this project?
From the original version of Igor Pavlov, the biggest problem for me is the lack of support for Zstandard.

**Comment by cielavenir** [comment]
@teoberi I think the next goal is https://github.com/jinfeihan57/p7zip/issues/141

**Comment by teoberi** [comment]
Good work! Compiles fine with the following changes.
1. UASM will be compiled/downloaded from:
https://github.com/Terraspace/UASM
http://www.terraspace.co.uk/uasm.html
The UASM executable is copied to /usr/local/bin
2. The following commands are executed:
`sed -i 's|MY_ASM = asmc|MY_ASM = uasm|g' CPP/7zip/7zip_gcc.mak`
`sed -i 's| -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE| -Wno-sign-conversion -Wno-unused-macros -Wno-conversion -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE|g' CPP/7zip/7zip_gcc.mak`
`sed -i 's|LFLAGS_ALL = -s $(MY_ARCH_2) $(LDFLAGS) $(LD_arch) $(OBJS) $(MY_LIBS) $(LIB2)|LFLAGS_ALL = -s $(MY_ARCH_2) $(LDFLAGS) -Wl,-z,noexecstack $(LD_arch) $(OBJS) $(MY_LIBS) $(LIB2)|g' CPP/7zip/7zip_gcc.mak`

**Comment by teoberi** [comment]
> @teoberi I think the next goal is #141

Totally agree with you!

**Comment by cielavenir** [comment]
#172 supports uasm (I did need to prepare https://github.com/cielavenir/homebrew-ciel/blob/master/uasm.rb beforehand though)

**Comment by tansy** [comment]
> However I have to say one thing: on [c65ff52](https://github.com/jinfeihan57/p7zip/commit/c65ff523fbbba1b0fc5624b29d44a37db34cf8a5) you ran some code formatter on CPP/7zip/Archive/7z/7zHandler.cpp right? it broke almost everything and I had to check conflict carefull

You can try remove leading white spaces and then compare; like this:
```
$ cat 7z2102-src____7zHandler.cpp | sed -e 's/^[ \t]*\(.*$\)/\1/' > 7z2102-src____7zHandler.cpp-1
$ cat p7zip-7zip_21.02____7zHandler.cpp | sed -e 's/^[ \t]*\(.*$\)/\1/' > p7zip-7zip_21.02____7zHandler.cpp-1
$ diff -rup 7z2102-src____7zHandler.cpp-1 p7zip-7zip_21.02____7zHandler.cpp-1 > p7zip-7zip_21.02____7zHandler.cpp-1.diff
```

**Comment by jinfeihan57** [comment]
@cielavenir Thank you very much for your work, but there is so much code to review that my computer can't display them all. So I did the update of p7zip21.07 myself. Please follow this branch. If you have any ideas you can submit the code on the new branch. I will close this merge request.

**Pull request closed without merging**
