### PR TITLE
add lzip decompression support

### PR DESCRIPTION
**Pull request by wdlkmpx**
The patch was written for (p)7zip-1604 by the lzip author
It was slightly modified to make it apply to this version..

lzip is included in:
- 7z
- 7za

Source: https://download.savannah.gnu.org/releases/lzip/7zip/
https://download.savannah.gnu.org/releases/lzip/p7zip_16.02_lzip-1.tar.bz2

I performed some tests and it seems to work fine..

### CODE REVIEW

**Comment by wdlkmpx** [comment]
I didn't add a test for lzip, there's a 200kb file to be added, but  I have a problem with `make test_7z`

The check/check*.sh scripts are not executable: `# chmod +x check*sh`

Then:
```
Creating archive: 7za433_7zip_zstd.7z

Items to compress: 6

System ERROR:
E_FAIL
ERROR during : /mnt/dev_save/git/p7zip/check/../bin/7z a -t7z 7za433_7zip_zstd.7z 7za433_7zip_lzma -m0=zstd -mx=22
makefile.common:104: recipe for target 'test_7z' failed
make: *** [test_7z] Error 1
```

This is my custom test for lzip (inside bin/) ...

```sh
#!/bin/sh
sha256sum 7z.exe > 7z.exe.sha256
lzip 7z.exe # creates 7z.exe.lz and deletes 7z.exe
./7z x 7z.exe.lz
sha256sum -c 7z.exe.sha256
```
7z.exe: OK

**Comment by jinfeihan57** [comment]
Are there any compilation errors or runtime errors here?  I don't understand your description very well.  And this is a linux program, why is it 7z.exe. It should be 7z without a suffix.

**Comment by wdlkmpx** [comment]
No, there are not. Everything is OK.

It's just that the Zstd encoding test fails on this 32bit linux system.
All the tests in check/test/ use a 7z.exe file.

I think this PR is safe to merge, it's just missing a test file, I mean the 200kb 7za.exe.lz file, but I think the test file should be ~30kb

I can add the test file in another PR
make test_7z needs some tweaks

Or I can add more commits to this PR

**Comment by wdlkmpx** [comment]
I found https://github.com/mcmilk/7-Zip-zstd

and the same patch was applied to that repo... LzHandler.cpp is 1-1 (identical).
It was added in commit https://github.com/mcmilk/7-Zip-zstd/commit/58069903d012d2a1ba833c6bb68d0108422757b4

**Comment by jinfeihan57** [comment]
If these are two unrelated things, please create a separate issue for zstd error. Thank you!

**Comment by jinfeihan57** [comment]
I will review this PR as soon as possible.:)

**Comment by tansy** [comment]
7z.exe in this ([p7zip_16.02_lzip-1.tar.bz2](https://download.savannah.gnu.org/releases/lzip/p7zip_16.02_lzip-1.tar.bz2)) patch is just old 7za.exe. I don't know why would anyone use this as test or anything but, back to the point, indeed it's the same what 7zip patch is ([7z1604_lzip-1.tar.gz](https://download.savannah.gnu.org/releases/lzip/7zip/7z1604_lzip-1.tar.gz)), at least `$p7zip_16.02/CPP/7zip/Archive/LzHandler.cpp` generated by these patches are the same.
What I can say is that I use aforementioned patch for years and it works fine. It's decompressor only though.

IMO it should be plugin, like `Rar.so` is, like most of those codecs should be. It would be better it the ware hot plugged rather than hardwired into the 7z.

**Comment by jinfeihan57** [comment]
I think it is necessary to keep the version that is already popular in the community. So I accept this version of PR.

**Comment by jinfeihan57** [comment]
Thanks.

**Pull request merged**
