### PR TITLE
Codecs dir

### LINKED ISSUE #25: Add Zstd as a ZIP compression method
First of all, thank you for your work on enabling p7zip users to use Zstd with the 7z archive file format.

I would like to use Zstd as a ZIP compression method because of the random access feature present in ZIP but not in 7z:
* For ZIP files, you can extract a file without having to process and decompress the entire archive.
* For 7z files, I believe random access is currently **not** implemented. However, it looks like the Apache Commons Compress library does have a "slow random access" implementation now. (More info: [COMPRESS-342](https://issues.apache.org/jira/browse/COMPRESS-342))

In addition, the [ZIP File Format Specification by PKWARE Inc.](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) has added the Zstandard compression method ID, and WinZip has added the Zstd method to the ZIP (ZIPX) format (please see [this PDF](https://www.winzip.com/static/images/pdf/winzip-comparison-chart.pdf) and [this webpage](https://support.winzip.com/hc/en-us/articles/115011811307-Unsupported-Zip-format)).

I found that the compression ratio of a ZIP file using Zstd Level 3 is similar to Deflate64 Level 5, while Zstd Level 3 performs (much) faster than Deflate64 Level 5.

I tried adding Zstd as a ZIP compression method ([please see my code here](https://github.com/ipaucek4680/p7zip/tree/zip-playground)) and it seems I can create, list and update a ZIP file using Zstd.

### PR DESCRIPTION
**Pull request by cielavenir**
Closes #25 #53 #141 #156 

This build (1a4e078513f44a071e03a7dfbfabe23203663a6b) should have the same capability as 7-Zip-zstd (except GUI):

- compression and decompression for Brotli, Lizard, LZ4, LZ5 and Zstandard within the 7-Zip container format
- compression and decompression of Lizard (.liz), LZ4 (.lz4), LZ5 (.lz5) and Zstandard (.zst) files
- handling of ZIP files with Zstandard compression
- included lzip decompression support, patch from: https://download.savannah.gnu.org/releases/lzip/7zip/
- squashfs files with LZ4 or Zstandard compression can be handled
- these hashes can be calculated: CRC32, CRC64, MD2, MD4, MD5, SHA1, SHA256, SHA384, SHA512, XXH32, XXH64, BLAKE2sp, BLAKE3 (lowercase or uppercase)

Additionally:

- It does support macOS/Linux :)
- Add PKImplode codec (can be disabled via -DDISABLE_PKIMPLODE_COMPRESS)
- Add Lzham codec
- Can build external Rar/PKImplode codecs
- Can build external hashers
- Codecs are now submodules
- Can build mingw edition on Linux
- External Zstd codec work with stock (p)7zip zip (specify -mm=zstd-pk or zstd-wz)

### CODE REVIEW

**Comment by teoberi** [comment]
`git clone --recurse-submodules -b CodecsDir https://github.com/cielavenir/p7zip.git`
`cd p7zip/CPP/7zip/Bundles/Alone && make -f ../../cmpl_gcc_x64.mak`

> make: *** No rule to make target 'b/g_x64/liblz5.a', needed by 'b/g_x64/7za'.  Stop.

**Comment by cielavenir** [comment]
@teoberi fixed (I tested only Alone2 and Format7zF)

**Comment by trounticonan** [comment]
If this PR is accepted, CMake will become a build dependency, as it is required by some of the additional codecs.

What do you think regarding the build system? Do you think it will be a good idea to add CMake support / drop GNU Make and switch to CMake?

**Comment by cielavenir** [comment]
@trounticonan https://github.com/jinfeihan57/p7zip/blob/7zip_21.02/CPP/7zip/7zip_gcc.mak uses cmake.
however i see master uses each c file. let me integrate it

**Comment by trounticonan** [comment]
Oops, you are right.

By the way, `master` has [CMake support](https://github.com/jinfeihan57/p7zip/tree/master/CPP/7zip/CMAKE) (which is based on vanilla p7zip), but `7zip_21.02` seems do not support CMake.

**Comment by teoberi** [comment]
`master` is dead.
https://github.com/jinfeihan57/p7zip/issues/156#issuecomment-891433297

**Comment by teoberi** [comment]
> If this PR is accepted, CMake will become a build dependency, as it is required by some of the additional codecs.

I don't know who should accept this PR, it seems that jinfeihan57 still doesn't answer.

**Comment by teoberi** [comment]
Amazing work! Thank you!
https://github.com/cielavenir/p7zip/actions/runs/2141292376

**Comment by cielavenir** [comment]
ok, so, even additionally:

- Added Balz and Bcm codecs (man, the performance does not look good...)
- Now CI builds linux(x64)/linux(x86)/macos(x64/arm64)/win32/win64
    - 7z.so/7zz are now built with DISABLE_RAR_COMPRESS=1 and DISABLE_PKIMPLODE_COMPRESS=1
- 7zz can access external codecs
- macos AES/CRC/SHA1 are assembled (Lz code is not assembled)

**Comment by cielavenir** [comment]
- And fixed `make -C CPP/7zip/Bundles/Alone2 -f makefile.gcc CXX=aarch64-linux-android-g++ CC=aarch64-linux-android-gcc CFLAGS_ADDITIONAL="-Wno-error -DNOTIMESPEC"`

**Comment by trounticonan** [comment]
> Added Balz and Bcm codecs (man, the performance does not look good...)

Do you have benchmarks of these two codecs and other codecs (e.g. [mcmilk's benchmarks](https://github.com/mcmilk/7-Zip-zstd#benchmarks=)?

**Comment by teoberi** [comment]
Although there are different releases (21.07.2, 21.07.3, 21.07.4) the version for 7zz, 7za and 7zr is the same, for example:

> 7-Zip (z) 21.07 (x64)

It would be very easy to add this in the p7zip/C/7zVersion.h file line 4
`#define MY_VERSION_NUMBERS "21.07.4"`

This change may cause problems in addition to the benefit of making it easier to identify the release?

**Comment by teoberi** [comment]
Maybe it could be implemented for the UASM build:
`sed -i 's|CC = gcc|CC = gcc -fcommon|g' gccLinux64.mak`
and
`sed -i 's|-Wl,-Map,$(OUTD)/$(TARGET1).map $(LDFLAGS)$|-Wl,-Map,$(OUTD)/$(TARGET1).map -Wl,-z,now $(LDFLAGS)|g' gccLinux64.mak`
The source of the changes is [openSUSE](https://build.opensuse.org/package/view_file/home:post-factum/uasm/PKGBUILD?expand=1) (with small additions for the second code).
The result using [checksec](https://github.com/slimm609/checksec.sh):

> RELRO
Full RELRO

**Comment by tansy** [comment]
> Closes #25 #53 #141 #156

How can you say it closes those issues mentioned when it just tweaks existing state, and definitely does not solve those.

Also you would do better if you separated these pull requests into separate topics.
I just stumbled upon someone [saying](https://github.com/Cyan4973/xxHash/pull/713#issuecomment-1122697407) it better than I could: 
_The benefit of having multiple PRs is to be able to merge them more gradually, as opposed to all-or-nothing. There are multiple topics in this PR, each one with its own points of attention.
I believe we can be more focused if we take care of them one by one._

**Comment by tansy** [comment]
> What will happen if @jinfeihan57 stops working on this project?

Seems like he already did.

**Comment by cielavenir** [comment]
> Also "your" LzHandler is a copy of [Diaz'es handler](https://download.savannah.gnu.org/releases/lzip/7zip/)

I just followed https://github.com/mcmilk/7-Zip-zstd/blob/master/CPP/7zip/Archive/LzHandler.cpp, so ask mcmilk.

> And also convension of files to DOS new lines (CRLF)

Original 7-zip source has CRLF new lines. So 7-zip derivatives (non-p7zip) should follow it.

**Comment by tansy** [comment]
> Original 7-zip source has CRLF new lines. So 7-zip derivatives (non-p7zip) should follow it.

Yeah, right, unix source should have dos line endings...
Even [ms visual studio uses LF](https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/AcousticEchoCancellation/cpp) only, unix new lines.
And the last one - it is p7zip, posix, *nix port of 7zip. If 7zip author wanted *nix port he would created it. He ever did. Until 2021 never did *nix port nor anything like that. So, no. The original, windows source is not a codex, it's just a guidance and under *nix we can follow unix phylosophy and make it simple and good for us.


> I just followed [...](https://github.com/mcmilk/7-Zip-zstd/blob/master/CPP/7zip/Archive/LzHandler.cpp), so ask mcmilk.

Original Diaz'es source has 0xC6, just like p7zip today, so ask him.

**Comment by jinfeihan57** [comment]
Thank you very much for your work, but there is so much code to review that my computer can't display them all. So I did the update of [p7zip21.07 ](https://github.com/jinfeihan57/p7zip/tree/p7zip21.07) myself. Please follow [this ](https://github.com/jinfeihan57/p7zip/tree/p7zip21.07) branch. If you have any ideas you can submit the code on the new branch. I will close this merge request.

**Comment by cielavenir** [comment]
@jinfeihan57 I wanted to start from clean state so that git 3-way merge works well. So I asked for https://github.com/jinfeihan57/p7zip/issues/179#issuecomment-1255673136 , but it is not done yet. It seems I cannot follow anything now.

One of my original goals was to provide Codecs/*.so including Balz and Bcm and they were resolved. It is also possible to copy them to jinfeihan57/p7zip distribution.

**Pull request closed without merging**
