### PR TITLE
P7zip22.00

### PR DESCRIPTION
**Pull request by jinfeihan57**
Update 7zip core to 7zip22.00

### CODE REVIEW

**Review by tansy — COMMENTED** [review]
I noticed, that in .gitattributes you set *.sln, *.vcxproj, *.vcproj, *.rc to CRLF line endings. Neither .lsn nor .vc(x)proj don't need to have dos line endings. Not even .rc files don't.
You can see it yourself - even microsoft is using unig LF in their own [examples](https://github.com/microsoft/VCSamples/tree/master/VC2008Samples/crt/RTC).

There are some extensions that do though - it's .dsp and .dsw in 7zip source tree. I have tried that and with unix LF they fail to be read by IDE. These should have been set up with CRLF line endings.

**Comment by jinfeihan57** [comment]
> I noticed, that in .gitattributes you set *.sln, *.vcxproj, *.vcproj, *.rc to CRLF line endings. Neither .lsn nor .vc(x)proj don't need to have dos line endings. Not even .rc files don't. You can see it yourself - even microsoft is using unig LF in their own [examples](https://github.com/microsoft/VCSamples/tree/master/VC2008Samples/crt/RTC).
> 
> There are some extensions that do though - it's .dsp and .dsw in 7zip source tree. I have tried that and with unix LF they fail to be read by IDE. These should have been set up with CRLF line endings.
I noticed, but there are too many files to modify. Is there any good way to achieve batch modification?

**Comment by tansy** [comment]
According to [git documentation on gitattributes](https://git-scm.com/docs/gitattributes) it should respect `.gitattributes` file in that directory then \`.gitattributes' in higher/est directory, then \`$GIT_DIR/info/attributes', which is most likely \`.git/info/attributes' in main repository directory.
Here is something about that as well.

So try to put \`.gitattributes' in main repository and main branch directory; it should work top->down. If it won't help then \`.git/info/attributes' in main repository directory.

**Comment by jinfeihan57** [comment]
@tansy It would be very helpful if you could provide the script.

**Comment by tansy** [comment]
Sorry, I forgot about that, then I couldn't find this thread but I found it and put it [here](https://gist.github.com/tansy/c4a1f7ea1019915b4263c024757d3ac4).
It's not perfect, just partisan script but keeps timestamps. If you have binaries, and want to copy them to destination directory as well, then copy directory as a whole first, then:
```
$ ./d2u-dir-1.sh <dir~> <dir>
```

I hope that's what you meant.

**Comment by jinfeihan57** [comment]
> Sorry, I forgot about that, then I couldn't find this thread but I found it and put it [here](https://gist.github.com/tansy/c4a1f7ea1019915b4263c024757d3ac4). It's not perfect, just partisan script but keeps timestamps. If you have binaries, and want to copy them to destination directory as well, then copy directory as a whole first, then:
> 
> ```
> $ ./d2u-dir-1.sh <dir~> <dir>
> ```
> 
> I hope that's what you meant.

Could not open this link.

**Comment by tansy** [comment]
> Could not open this link.

[d2u-dir-1.sh](https://gist.github.com/tansy/c4a1f7ea1019915b4263c024757d3ac4)

**Pull request merged**
